
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  sources:
    - chart: mlflow
      repoURL: 'registry-1.docker.io/bitnamicharts'
      targetRevision: "1.4.22"
      helm:
        releaseName: mlflow
        valuesObject:
          image:
            repository: bitnamilegacy/mlflow
          waitContainer:
            image:
              repository: bitnamilegacy/os-shell
          postgresql:
            image:
              repository: bitnamilegacy/postgresql
          minio:
            image:
              repository: bitnamilegacy/minio
          volumePermissions:
            image:
              repository: bitnamilegacy/os-shell
          tracking:
            service:
              type: NodePort
              nodePorts:
                http: "30090"
            auth:
              enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlflow
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
