
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-manifests/nginx
    repoURL: 'ssh://git@github.com/swamysrivathsan/llmops-nvidia.git'
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
